
KAFKA_REST_URL = "dp_kafka_rest_dev.internal.dev.licious.app"
FLASK_SERVICE_PORT = 8000

[[URL_MAPPING]]
route = "/ingest/bank"
method = "POST"
topic="transactions"
endpoint = "gate"
auth = "Token"
token_head = "X-AUTH"
token_key = "BRANCH_TOKEN"

[[URL_MAPPING]]
route = "/ingest/advsior"
method = "POST"
topic="advisors"
endpoint = "gate"
auth= "Basic"
user_env = "CT_USER"
pass_env = "CT_PASS"
